name: app_datvexemphim
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  go_router: ^14.8.0
  shared_preferences: ^2.5.2
  smooth_page_indicator: ^1.2.1
  dio: ^5.3.2
  http: 1.3.0
  flutter_spinkit: ^5.2.0
  icons_plus: ^5.0.0
  carousel_slider: ^5.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

   